### PR TITLE
Version 1.4.7

### PR DESCRIPTION
**Pull request by Tiny-Giant**
Major updates including bugfixes related to #23 #24 #26 #27 #28. Also, now you can save multiple chatrooms and chose from a list. No more switching tabs to get the right URL. Unfortunately, this doesn't save across sites, so for now you have to enter your rooms the first time you open it on a site.

Try it out [here](https://github.com/SO-Close-Vote-Reviewers/UserScripts/raw/bloody/SECloseVoteRequestGenerator.user.js)

### CODE REVIEW

**Comment by gunr2171** [comment]
I'll just accumulate issues I find with this PR here instead of as full issues:

* The first menu item says "Target room: SO Close Vote Reviewers", but "Target room:" is the only thing that is clickable. Clicking the room name does not expand / contract the menu item.

* You can't add a duplicate room entry, which is nice, but you can't add it if you just (without refreshing) removed all the saved entries.
  1. Start with the CV room
  2. Add the testing room
  3. Remove both
  4. Attempt to add testing room, won't let you
  5. Attempt to add CV room, allowed

  This might need some further testing, because it seems to allow the second room you try to add back.

* Clicking "Send request" shows a javascript `window.prompt` instead of the input box, and no banner is shown telling the request is successful.

OH OH OH, that's what "fancy" and "classic" mean. Window.prompt vs input boxes. Oh. Might want to label that to be more explicit about what it does. All previous bullet points were done with "Classic". We might also want to default to "Fancy".

* (Test room, append yes, fancy) date/time and user are not appended to request.
  

I'll do some more testing later.

**Comment by gunr2171** [comment]
* The banner at the top sometimes has a problem when it leaves, and there is a whitespot at the top of the page.

**Comment by mogsdad** [comment]
Doesn't run in Firefox; I haven't checked the delta yet, but maybe the requires got dropped, and the script is running before jQuery? Downgraded to 1.4.6 and things are OK - hardly scientific, but doesn't appear to be my environment at fault.

**Comment by Tiny-Giant** [comment]
Thanks for the bugs reports guys. I'll get on it right away.

**Comment by Tiny-Giant** [comment]
All of these issues *should* be fixed. Let me know if there are any outstanding issues.

**Comment by kevin-brown** [comment]
Testing this out for the first time. I just clicked the "set room" button, which gives you the room list

image

Just by clicking the link, it reset my default room (to a null-like value). And I also can't easily select the one I wanted because you appear to be listening to the change event (I don't want to change it).

Going further, trying to send a request when there is no selected room passes and gives no error.

image

Unfortunately I just tried it again and couldn't get it to fail, so I might have messed something up the first time.

**Comment by Tiny-Giant** [comment]
@kevin-brown I was able to reproduce the title not changing back to the room name if after clicking on an already selected item, that was an oversight of UI, but the room still would have been set. I have not been able to reproduce it not sending. I'll keep an eye on it though, if it happens again please let me know.

**Comment by mogsdad** [comment]
I've reproduced both of Kevin's problems, wish I'd seen that he'd posted before.

I cannot send at all. Doesn't matter what the room is.

**Comment by Tiny-Giant** [comment]
That's just weird, did you do something before this happened? Does localStorage.clear() kill the issue?

**Comment by gunr2171** [comment]
Issues found in chat, putting gifs here because chat doesn't like the source (403's for some reason)

* You will see "set target room:" if you remove the last room
  1. Open the menu, the second menu item is the name of the room
  2. Delete the only room, banner will appear telling you that you can't
  3. Close the menu without refreshing and open again
  4. Notice that the second menu item says "Set target room:"
  5. The menu item corrects itself if you open the "send request" option or open&close the room option.


* You can add a `http` and `https` of the same chat room. It seems they both allow messages sent, but they show as the same chat room name in the menu.

* Backticks in titles are not escaped, but I don't think that's a problem.

**Pull request merged**
