### PR TITLE
Fixes issue 106

### PR DESCRIPTION
**Pull request by Shah-Nisarg**
Copies/Displays the request text if it fails to send the request.

https://github.com/SO-Close-Vote-Reviewers/UserScripts/issues/106

### CODE REVIEW

**Comment by makyen** [comment]
I have not yet actually tested this. I expect to do so on various browsers.

As you are aware, [my position on automatically copying to the clipboard in this error condition has changed](https://github.com/SO-Close-Vote-Reviewers/UserScripts/issues/106#issuecomment-333321728). I'm sorry to do that after you've written code. Unfortunately, the issue was raised as I was at the end of my day. I was literally nodding off in front of my keyboard.

Generally, the code looks good. As mentioned, I still need to actually test for functionality/look-and-feel, etc.

I see you've chosen to place the request text within a `<small style='font-size: smaller'>`. I'm interested in why a `<small>` instead of a `<span>`. Just curious.

The bookmarklet used a `<textarea>` to hold the request text. There were multiple reasons to do so. Some of the reasons don't matter to the userscript. Those that are valid in the context of the userscript are:
* The notification with the textarea is *very* different in look from any other notification. This should help to make the user actually pay attention and not just click to dismiss the notification. Even with the fact that the notification doesn't auto-dismiss, I think that visual difference is valuable. A textarea is also something that users have been preconditioned to know they are to interact with it in some way.
* The request text is *distinctly* different from the rest of the notification. This allows the user to more clearly see exactly which text is their request. This could be handled with using an alternate `style`. However, if we do that, then we need to be mindful that the user may have a non-stock color theme installed and/or may have other color issues (i.e. setting specific colors is not the best choice). You do us a smaller font. While that does make the request text different, it doesn't make it pop-out to the user. Frankly, the stock (light) orange background color with white text is, IMO, a poor choice on SE's part as it doesn't provide enough contrast (2.14:1). If they really wanted to go with that orange background, black text would have been a better choice (9.81:1).
* If, for some reason, the user is manually selecting the text, a textarea makes it harder for them to also select the rest of the notification at the same time. They can do so, but they have to work at it.
* It makes it easy to programmatically select the request text for the case where the user must manually copy the text. It's still possible to programmatically select the text when using non-input elements, but doing so is more complex.

We don't need to use a textarea here. I'm certainly open to other ways to format the request text. Not trying for an alternative in the bookmarklet was at least in part due to the complexity constraints imposed by a maximum of 2088 characters. However, I would like to address the user-interface issues mentioned above.

It might also be a good idea to include text in the notification to the effect of: "... (see console for details). ... [request text]" That way the user knows there is more information available, if they want it. People should already know to check the console, but it doesn't hurt to be explicit.

**Comment by Shah-Nisarg** [comment]
v1 notification on error
I am thinking about something like this. I changed the wordings a bit (error code, see console, click here to copy etc.) 

Another alternative is this:

v2 notification on error


Btw, I used smaller text because it takes up too much space already. That's one of the reasons I like the second image above. I am also considering whether or not to have a `height: 10px` on the textarea or not. Pro: Takes up even lesser space. Con: It will hide the second row of the text, so the user might require a second before they realize that the text is the markup they are supposed to copy.

**Comment by makyen** [comment]
They both seam to cover the bases we desire. I'm on the fence as to which layout.

I'd probably use the text "copy to clipboard" rather than just "copy" or "click here to copy". The "click here" part is implicit in it being link-style.  Alternately, just "copy" and a tooltip that has something more verbose, like "click to copy the request text to the clipboard".

I'd also word the failure as "Failed to retrieve", or "Encountered an error while retrieving", rather than "Failed retrieving". "Failed retrieving" is awkward wording.

It's probably a good idea for us to select the request text, so the user can just hit <kbd>Ctrl</kbd>-<kbd>C</kbd>. We have people that use this primarily with both hands on the keyboard, in addition to those that use keyboard and mouse. Us pre-selecting the text should make it easier for that use.

I would not limit the height of the textarea. This is an error/exception, which the user should be dealing with when it occurs. I don't have a problem with this case having a large notification. Normal operation has a single line notification which is only displayed for a brief time. Having the exception case being clear (significantly larger than the normal notification and not auto-dismissed) is, IMO, a good thing. Keep in mind that this is something that users will have had work properly hundreds or thousands of times. Visually making it *really clear* that what they were expecting to happen didn't happen is a good thing, IMO.

Yeah, don't change the colors. We have users who have installed various color themes. If we apply colors, we have to take that into account. It's better to just use the default colors, even if it's not that great of a choice on the part of SE.

**Comment by Shah-Nisarg** [comment]
Here's how it looks after the recent changes:

v3 notification on error

**Comment by makyen** [comment]
### Layout
* "Copy" should be all lower case, as that fits SE's UI better. Along these lines, I'd probably prefer the layout either [without parenthesis](https://i.stack.imgur.com/kCZhH.png), or [with parenthesis, but prior to the colon](https://i.stack.imgur.com/UAPVV.png).

* Having the actual message displayed in the console state "See console (F12) for details." could be mildly confusing. Also, it should be "See the console...".

* Consider having the "F12" in `<kbd>` format (e.g. <kbd>F12</kbd>), or not including "(F12)" at all. Those people who are interested, probably already know how to open the console.

* Don't use the smaller font here (i.e. `style='font-size:smaller;'`). It worsens the visibility issue which already exists with using the text/background color combination SE chose for notifications. While you and I might prefer smaller text, having the text be smaller does not appear to have much tangible benefit in this situation, and has the potential of making the notification harder to read for some users.

* "...the request text to clipboard" should be "... the request text to the clipboard".

### Code
* Please don't have spaces on unused lines, or spaces at the ends of lines. When edited in the default Tampermonkey editor it looks like [this](https://i.stack.imgur.com/m7pDq.png). Having those spaces will just end up with someone else removing them at some point.

* The case where the copy-to-clipboard fails is not detected/handled. Obviously, this means the user is not informed that copying to the clipboard via the "copy" button failed. If we offer the "copy" button, when the copy-to-clipboard fails, we should indicate to the user, in some way, that the copy failed.

  However, the cases where it fails to copy should be significantly reduced vs/ the bookmarklet. Most browsers permit copying to the clipboard from within a user-initiated-event handler, which the `onclick` handler obviously is. One of the issues with the bookmarklet is that some browsers don't consider clicking on a bookmarklet to put the resulting code into a handler for a user-initiated-event.

* The `try`/`catch` block is not needed here.

  In the bookmarklet, the outer `try`/`catch` block is used primarily to handle the case where `StackExchange.notify()` is not valid (yet) and, through the use of `if (!success) throw 1;`, to also detect that the copy-to-clipboard failed. Falling back to `alert()` is handled by the inner `try`/`catch` block which falls back to using `alert()` when the second `StackExchange.notify()` throws a (second) error. Looking at the bookmark code, I, clearly, need to provide more comments to explain what's going on in that section. It's a bit more complex than would normally be desirable due to using this dual functionality to reduce the number of characters used.

  You do not need to be concerned about the possibility of `StackExchange.notify()` not being valid. That is (actually, will be) handled in `notify()` (yep, another thing changed in development). Thus, the `try`/`catch` block is not needed for this code. However, detecting success/failure of `document.execCommand('copy');` is desirable.

* Usually, I strongly recommend against using either `Element.on[event]` or the HTML event attributes, but, other than the copy-failure case not being handled, I don't have a problem with using it in this specific use case. However, do keep in mind that code which you place in that `onclick` attribute executes *in a different context* (i.e. the page context). Thus, you can not directly interact with any userscript code (i.e. can't call functions/access variables defined in the userscript code).

* For mid to long HTML text, please use a multiline string with the HTML text formatted similar to how it would be formatted in an HTML file. This makes it much easier to edit/maintain. In other words, instead of:
  ```JavaScript
  message = message + " <br/><br/><span>Request text: </span><a href='#' onclick=\" $(this).parent().find('textarea').select();document.execCommand('copy');\" title='Click here to copy the request text to the clipboard.'>(Copy)</a><br/><textarea style='width: 95%;'>" + requestText + "</textarea><br/>";
  message = "<span style='font-size:smaller;'>" + message + "</span>";
  ```
  Use something like:

  ```JavaScript
  message += "" +
      "<span style='font-size:smaller;'>" +
      "    <br/><br/>" +
      "    <span>Request text: </span>" +
      "    <a href='#' " +
      "        onclick='" +
      "            $(this).parent().find(\"textarea\").select();" +
      "            document.execCommand(\"copy\");" +
      "        '" +
      "        title='Click here to copy the request text to the clipboard.'" +
      "        >(Copy)</a>" +
      "    <br/>" +
      "    <textarea style='width: 95%;'>" + requestText + "</textarea>" +
      "    <br/>" + 
      "</span>" + 
      "";
  ```
  While it's not as beneficial in this case as it is when the HTML text has more structure, it still makes it easier to read/edit/maintain.

  I'm aware that using a multiline string like this this does not match what's currently done in other locations of this script. However, I've already changed all those in my development branch. I was tempted to not mention this issue (and just change it in my development branch), but using a multiline string like this is quite beneficial for maintainability, and should be something we encourage in new contributions.

  In the example, I changed the quotes used for the `onclick` attribute to match using `'` on the values for the other attributes. It makes the text a bit longer, but I feel there's value in the consistency.

  There are many ways to write multiline strings in JavaScript. The one I used above is just my personal preference, due to being significantly faster than the Array `.join()` representation and having broader compatibility than template literals. However, as long as IE compatibility is not desired, template literals are probably better at this point. I would prefer not to use template literals in this script at this time. Using empty strings at the beginning and end merely allows lines to be added/removed without concern for them being on the first or last line.

**Comment by Shah-Nisarg** [comment]
@makyen Thanks for the suggestions. I particularly liked the idea of formatting the HTML text. I had to do it slightly differently to avoid adding spaces around "copy" word.

I'm not quite sure about the part about leaving blank spaces on empty lines. I've never met anyone that cleans those spaces consciously. Or it could be because Visual Studio that does it internally. At home I am using Brackets these days, so I didn't notice.

In the error handler for `document.execCommand` part, I have tried to shift the focus back to the text area and select the text - as the `alert` will take away the focus and de-select the text. Peculiarly enough, I had to place it in a `setTimeout` or it wouldn't work. At the moment, I'm not sure why that part of code doesn't work without it. My guess is that the alert hiding animation might be taking non-zero time, and the `elem.select()` and `elem.focus()` might be getting executed before the `alert` takes away the focus. Do you know the reason? I'm using Chrome btw.


I've tried some other methods of giving "Copy succeeded" or "Copy failed" notifications, before settling on `alert`. 

- For instance, giving another `notify` is not useful as it hides the current notification. 
- I tried modifying the text of `<a>` from `copy` to `copy - success` or `copy - failed`. But it doesn't look good to me.

**Comment by makyen** [comment]
Sorry for the delay in getting to this. I've been busy in real-life and my spare coding time has been occupied trying to get out a new version of Top Navigation Choices to solve some things with the network wide roll-out of the "new" SE top navigation bar.

Yeah, using a multi-line string for formatting HTML text (and CSS) makes those much easier to work with. Sorry, I should have mentioned the potential issue with needing to not have extra spaces around the "copy". 

What error are you attempting to catch with the `try`/`catch` block? In the bookmarklet, the only reason `try`/`catch` blocks are used is that `StackExchange.notify` might not exist at the time which the user clicks on the bookmarklet. I'm not immediately seeing what error you are attempting to catch here. The need to catch the possible issue with `StackExchange.notify` doesn't exist in this code (you can assume it's handled elsewhere, even though it's not actually in the code you're looking at).

Instead of doing `$(this).parent().parent().find("textarea.SECVR-request-text")` multiple times, you can just save the reference which you got from `$("#" + notificationId + " textarea.SECVR-request-text")` in a variable. It should also make the code more robust by not relying upon the actual structure of the DOM with the `parent().parent()`.

While saving such references to reuse them is not necessary, it's a good habit to get into, particularly when using jQuery (and some other similar libraries, etc.). The reason for this is that jQuery makes it very easy to look for things in the DOM by using selectors. By default, such searches look for elements throughout the DOM, which is (relatively) expensive when using selectors (e.g. searching the DOM for all elements with a single class is 10x faster using `getElementsByClassName()` than it is using selectors (`querySelectorAll()`, which is what jQuery is based on). While it's usually not necessary to go too far out of your way to limit such searching, it's of benefit to use a variable to store such references, as long as the results of such searches won't change.

In this case, using the `notificationId` in `$("#" + notificationId + " textarea.SECVR-request-text")` is not needed, as `notify()` forces the script to have only one notification open at a time. A possibly better way to do this, which still maintains the possibility of having multiple notifications, should that be changed script-wide, would be `$("textarea.SECVR-request-text").last()`, which will give you a reference to the notification which was most recently added containing a textarea with the appropriate class (the most recent notification is later in the DOM than earlier notifications).

As to the `setTimeout()`, I recall it being needed. My first take on why was similar to yours. I'll have to look at it in more detail to refresh what I remember about the issue.

An `alert()` should work, but isn't the most desirable way to notify the user. However, in this case, it's probably what we may have to use. I'll look at the other possibilities when I test the script on various platforms.

I still need to do testing on various platforms. I'll probably be able to get to that in the next day or so.

**Comment by Shah-Nisarg** [comment]
Yeah, I've also been somewhat busy lately. I will try and give you the updated script over the weekend.

**Comment by Shah-Nisarg** [comment]
@makyen  In addition to your suggestions, I've also simplified the selector for "copy" button's click handler to `$("a.SECVR-copy-to-clipboard").last()`. 

I'm somewhat surprised that I can save reference to `$("textarea.SECVR-request-text").last()` in a variable, and access it inside the click handler - which is an anonymous function. I had been assuming that it would run under a different context.

As an alternative, you can check [GlyphSearch.com](https://glyphsearch.com/), which has a slightly different way of presenting such text. They use prompt boxes like this: `prompt("Copy to clipboard:", "<i class=\"fa fa-500px\"></i>")`. So we could be giving just a copy button, and in case it fails, we could present that `prompt` dialog.

**Comment by makyen** [comment]
@Shah-Nisarg, I'm sorry for the delay in my getting back to this. I believe I've cleared the real-life stuff which has been taking up the majority of my time over the last week. However, I'm quite tired at the moment, so I need to get some sleep prior to diving into this (reviewing/testing). I should be able to work on this when I wake up tomorrow.

As to being able to store the variable: the variable is defined in the larger scope which also contains the anonymous event handler. In general, you will have access to variables defined in scopes which contain the scope in which you are currently operating, unless you've defined a variable with the same name in your current scope. Thus, you have access to variables in the containing scope from within the anonymous event handler.

Contexts... more when I wake up.

**Comment by Shah-Nisarg** [comment]
@makyen The delay is quite alright. 

Also, don't worry about explaining these concepts to me. I'm afraid there is a lot I don't know yet, and not only in Javascript. I will learn these concepts with time. :)

**Pull request merged**
