### PR TITLE
A script to show all open, yet to vote cv requests which belong to the users favorite tags from the day.

### PR DESCRIPTION
**Pull request by AjayBrahmakshatriya**

### CODE REVIEW

**Comment by AjayBrahmakshatriya** [comment]
@gunr2171 I agree with the first point. The "crossed" out question ids can be put into the browser's localStorage for filtering it out and the id can be removed from that list when it doesn't appear in the transcript (change of day or request graveyard).

**Comment by makyen** [comment]
### Getting actual close votes has disadvantages
To get the actual close votes you have to fetch the actual question page (as you do), use the real-time fetch URLs (question/answers/votes) [this would probably be better than fetching the entire question for your current use, as it only fetches just the question or answer HTML], fetch just the question's close-vote dialog (hard rate-limited to 1 per 3s), or use the [OAuth 2.0 flow](https://api.stackexchange.com/docs/authentication) to obtain a user authentication token from the SE API (which will then allow you to get private information like votes). Each of those has disadvantages: 

* The question and real-time fetch URLs have [significant undisclosed rate-limits](https://meta.stackoverflow.com/questions/353906/has-the-allowed-request-rate-rate-limit-been-changed). If tripped, the user is then denied all normal access to SE questions for a period of time. For what you are doing, if the user has a number of tags defined and there are a large number of cv-pls for those tags, it's likely that this will be tripped, as you do not rate limit your requests for question pages. My experience has been that 1 request every 500ms was too fast. So far (tested in a change to Magic Tag), 1 request/s appears to be OK.
* Fetching the question HTML requires you to scrape the HTML. You are currently not accounting for some cases. For instance: migrated questions, locked questions, and actually closed questions (not just "on hold"). Any of those cases will cause your current code to fail to detect the current state of the question or to present a question to the user which is not actionable.
* For using the SE API with a user access token, the user is only permitted to have 5 such tokens authorized at a time.

### We should not be using actual close votes to determine show/no show cv-pls requests
As @gunr2171 has alluded to, the person actually voting to close any specific question is a personal choice. As is stated in the FAQ:

> cv-pls means "close vote please", not "close vote or I'll stab you."

We should *not* keep the cv-pls in front of people's face until they vote. At most, it should be only until they evaluate the question and make a choice to vote, or not.

Personally, I handled this by tracking when the person visits questions from a link in the transcript or the request search page. The question ID and the time of visit are kept in user script storage for 7 days and then forgotten (7 days was chosen because it's 2x+1 the normal 3 day life of a cv-pls request). As I write this, I realized that the question should probably no longer be considered "visited" if it's been edited after the visit, or at least he user should have the option to automatically not consider such questions visited.

One of the significant advantages of not looking at actual close votes is that the information you need  (closed/unclosed, locked/not locked) can be obtained with a single call to the SE API for up to 100 questions at a time.

**Comment by makyen** [comment]
FYI: The RegExp you are using to detect question IDs needs a bit of work. Currently, it detects neither HTTP URLs, nor protocol-relative URLs. In addition, it requires a `/` after the question ID, which is not actually required in a valid question URL. In other words, your RegExp is more strict than what is needed to have a valid URL to a question. For instance, you might use:

    var id_regex = /(?:https?:)?\/\/stackoverflow\.com\/q(?:uestions)?\/([0-9]+)/;

[Note that this changes your `(uestions)` to a non-capturing group, which will change a bit of how you handle `matches`.]

If you choose, given that you are detecting against the `href` property, you could just not include the `(?:https?:)?` in the RegExp at all, as excluding other protocols (e.g. ftp) is a low priority. Personally, I'd leave it in, but, choosing to not have it isn't unreasonable.

In addition, it would be better to exclude tag URLs and then search through links rather than assume the question URL is the 3rd one in the message. This will fail/operate in an undesired manner if there are more than 2 tags, or if the request has more than one question link (e.g. it's not uncommon for people to include the duplicate-target in "Duplicate" cv-pls requests, in addition to the question which is actually intended to be closed). An alternative here is to just process all links in the request looking for question links. Your RegExp should already properly exclude non-question links (e.g. tags, users), which would allow you to use it to exclude non-question links.

Also, cv-pls requests are considered valid if the URL is just in text, as opposed to being an actual link. While rare, this does happen from time to time. You should consider if you want to search for question URLs which are in text instead of being an actual link.

**Comment by AjayBrahmakshatriya** [comment]
@makyen @gunr2171  Following changes are made in the latest commit -

1. Moved the position of the CV requests from right side bar to a popup window whose visibility can be controlled by a button in the chat area.

2. Added an ignore button with each CV request to mark the request as not interesting. This removes the  request from the list and doesn't ever appear again. Presently no mechanism to undo this or bring back a request in case it is changed. Looking into timestamp based options suggested by @makyen .

3. Changed the RegExp for url to the one suggested by @makyen. Also changed the url selection logic to look at the first anchor tag with url that matches the pattern for a question URL.

Still have to strengthen the logic for determining whether a question is actually closed. The unauthorized SE API has a very low limit of 300 requests (per day?). 
Regarding the rate limit, can temporarily fix the issue by throttling requests to 1 per second. 

Both the problems can be together fixed by moving to authenticated SE API.

**Comment by gunr2171** [comment]
Oh, minor note: the name of the file is "FavoriteCVs" and the UserScript name is "Important Cvs" Might want to have that more descriptive.

**Comment by makyen** [comment]
FYI: With respect to SE API requests, there are 3 (generally available) conditions for what quota is granted (See [Throttles/Rate Limiting](https://api.stackexchange.com/docs/throttle)):
1. 300 requests/day per IP with no access key. Shared by everything on that IP which doesn't have an access key. This is intended to facilitate early testing. The expectation is that scripts/apps which go beyond initial testing will obtain an access key (free and automatically obtained when you fill out a form).
2. 10,000 requests/day per IP for all requests with an access key, but without a user access token. The 10k requests are shared for that IP across all such scripts/apps/etc.
3. 10,000 requests/day per user access token. These 10k requests are available to the single script/app/etc. which holds that access token for that user. Users can have up to 5 applications authorized at a time.

Access keys can be automatically obtained by [registering your script on Stack Apps](https://stackapps.com/apps/oauth/register). This process is also the beginning of registering to be able to go through the OAuth 2.0 process to get a user access token. To get an access key for your script you have to fill-out and submit that page, but you don't have to go through the full process to fully enable the use of OAuth 2.0. You will have the ability to change/update all of the information provided after it's submitted the first time. [Note: The entry line that's required and not obvious is the OAuth Domain. The default to use is `stackexchange.com/oauth/login_success`.]

User access tokens are obtained through the OAuth 2.0 flow within your script/app. Scripts/apps are individually authorized by each user, granting the script the right to perform privileged actions as if it was the user. There are additional requirements to fully enable this flow (e.g. you must post a question on Stack Apps describing your script/app.). I'm not recommending you go through getting user access tokens, just providing information.

**Comment by AjayBrahmakshatriya** [comment]
@rschrieken Yes, all the requests going to the main site are throttled to 1 request per second, which @makyen  stated from previous projects is more than enough. I have been using the script since it was fixed and haven't run into the rate limit ban.

**Comment by AjayBrahmakshatriya** [comment]
@makyen All the issues from the previous comments have also been addressed.

**Comment by makyen** [comment]
### The data I have on the rate-limit is very limited
To be a bit more precise: I stated I have only two data points from *some* testing with Magic Tag (a modification to auto-skip questions on which the user can't act upon): 
1. That 1 real-time URL request every 500ms did result in my routinely triggering the rate-limit lockout.
2. That 1 real-time URL request every 1s, hasn't triggered the rate-limit lockout

Note that these data points don't necessarily account for the potential of having activity in multiple tabs. I don't consider my testing to be even close to thorough. So far, it's been more of "oh that didn't work, lets try this". In addition, the 1/500ms testing was performed while chat was on Fastly, which it currently is not, but is expected to be in the future (see [question I previously linked](https://meta.stackoverflow.com/questions/353906/has-the-allowed-request-rate-rate-limit-been-changed) for a bit more info). In other words, the test environment changed between my various trials. It also means that the rate-limits are a target which is planned to be moving.

### Triggering the rate-limit lockout is negative for users
Triggering the rate-limit lockout is significantly negative for anyone using the script. The lockout completely prevents normal use of Stack Exchange Q&A (not chat) for 10 minutes to 1/2 hour (based on my memory of the lockout length, but I've never actually timed the lockout period). I also don't know if the user is more significantly penalized if the rate-limit lockout is triggered multiple times within a certain period. Having progressively longer rate-limit lockouts for repeat detections from a single IP is something I'd expect.

It's important to not end up in a situation where the user is locked out, but where they have no clue as to why. One of the issues is that your requests for question pages are generally not obvious to users (at least the last time I looked at your code). Your script *may* need to: A) Detect a lockout and cease function. B). Report to the user that the script probably contributed to the issue. C) Get authorization from the user to continue processing.

### Need stress testing/review (I'll try to do some testing by early/mid UTC-Wed.)
The downside for users of a lockout is fairly significant, even if there are no additional, longer term, levels of lockout for repeated detections from a single IP. I'd like a bit more time for testing and thinking through probable and worst case scenarios.

I've been thinking of some good ways to perform some stress testing with this, but I haven't yet gotten to doing so. I also need to do another full look-through of the code. I may be able to work on it tomorrow (late today UTC to early tomorrow UTC), but tomorrow has a considerable amount of stuff that's been previously scheduled, so I'm unsure if I will be able to do so. My expectation is that I should be able to get to it on my Tuesday (late UTC-Tuesday to early UTC-Wed.).

### SE may have a problem with this approach
I also have concerns as to what SE would think of this approach. My understanding is they have been against scripts fetching SE pages the user is not actually visiting in order to scrape information. Having a way for scripts to obtain such information without fetching pages is, after all, why they created the SE API. I believe they don't have a problem with scripts obtaining data from pages which the user actually visits, but they've been against scripts fetching pages the user isn't visiting to obtain information.

## Additional alternative approaches (see prior comments for others)
The data you need from question pages is the IDs of questions on which the user has cast a close-vote (as best as can be determined from question page HTML). Both of the following would allow you get the information as to what the user has close-voted through normal in-page voting (or anything designed to mimic such votes from those pages).
1. Your script could also run on all SO question pages, the close-vote review queue, NATO (with NATO Enhancements), Magic Tag, etc. and watch for close votes on those pages.
2. The update to the Close Vote Request Generator (CVRG) script which I'm working on already detects normal in-page close votes (in the above mentioned cases, and others). Currently, the only thing it does with that information is collect the close reason for use in a possible subsequent cv-pls request. 

   It would not be difficult to make the CVRG report that a question was close-voted to other scripts running on the chat page (e.g. yours; I don't mean posting votes in chat messages, just communicating to other running scripts). This could be done either in semi-real-time, or as cumulative for X time-period upon request from another script, or store them in localStorage (I don't really like the localStorage option). I've been a little reluctant to suggest doing this, as this has some privacy issues. However, those issues can be mitigated (e.g. the user can have the option not to have the information shared). Doing this would remove the need to fetch the question pages, but would require people to also be running the CV Request Generator in order for your script to function.

**Comment by AjayBrahmakshatriya** [comment]
@makyen Since multiple requests (one per cv-pls) is such a burden, maybe we can look at 
`https://stackoverflow.com/users/current/?tab=votes` to determine the status of vote from the user. I am not sure how frequently this is updated. I can check into it. But this can give us the information of all(?) the questions in a single request.

**Comment by makyen** [comment]
If you need to know the votes on multiple questions, fetching a single page from the profile is probably better than fetching multiple question pages (from the point of view of load on servers). On the other hand, fetching a single question page is probably better than the fetching the page from the profile.

As to how often it's updated, I'd be surprised if it wasn't real-time.

**Comment by AjayBrahmakshatriya** [comment]
@makyen I did check how often it is updated and it seems to be real time. Along with this request we would also have to send a request to the API to check the open/closed status of the question. Can be done without user authentication though. Now the IP wide and app wide limit of 10000 might not be enough in that case.

**Comment by makyen** [comment]
10,000 requests not enough??? Do you mean for your script alone? Each request allows you to obtain information on up to 100 questions. That's 1,000,000 questions per day (max). I don't see how you would use that many requests. I understand that you probably won't fill a request with 100 questions every time, but how often are you expecting to update? 10,000 requests is an average of one request every 8.6s.

If you are performing more than 1,000 SE API requests in a day, something is wrong/non-optimal in how you are organizing requests, or about how real-time you are trying to be. I obtain question/answer data for all questions and answers linked in the SOCVR room and keep that data updated in semi-real-time with a few hundred requests per day (usually; it varies). You can/should do things to reduce the amount of updating you do (e.g. not update unless the user has that tab visible (not just open)). Admittedly, there are use cases where the user may have multiple tabs open, which can chew up more requests (which could be mitigated by sharing the requested data between tabs).

There are other restrictions as to the max rate at which you should be performing identical SE API requests (*identical* requests are not to be made more often than 1/minute). Performing multiple different requests rapidly is OK, but you have to obey any `backoff` time which the API tells you to delay.

But, there are certainly circumstances where the 10,000 requests will be consumed in a day. Your code should be designed such that it minimizes the requests that you make. This is particularly true given that the IP quota may be shared by multiple applications/scripts, or multiple users.

**Comment by AjayBrahmakshatriya** [comment]
@makyen  10,000 seem fine for a single user. It is just that since it is IP wide, I thought maybe in an office like setting where the same IP is used, the quota might expire. But seems unlikely that many users would use the script on a network. I have read about the back off for similar requests, so that I will take care of. I think at this point, this is the right way to go. I will update the logic soon.

**Pull request closed without merging**
